language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_mailer/ framework/app/libraries/li3_mailer
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - git submodule add https://github.com/swiftmailer/swiftmailer.git libraries/swiftmailer
  - cd ../../app/libraries && git clone -b dev git://github.com/BlaineSch/li3_quality.git
  - cd ..
  - echo "Libraries::add('li3_mailer'); Libraries::add('li3_quality');" >> config/bootstrap/libraries.php
  - echo "Libraries::add('swiftmailer', array('prefix' => 'Swift_', 'bootstrap' => 'lib/swift_required.php'));" >> config/bootstrap/libraries.php

script: ../libraries/lithium/console/li3 test libraries/li3_mailer/tests && ../libraries/lithium/console/li3 quality syntax --library=li3_mailer
